/**
 * Expo config plugin — let the Android build reach the UAT API over HTTPS.
 *
 * WHY THIS EXISTS
 * The UAT server (https://apimacuat.zyncbook.com) presents the stock **self-signed Plesk
 * certificate** (subject C=CH, O=Plesk, CN=Plesk — no SAN for the host, issued by itself).
 * Android rejects it with CertPathValidatorException, so every API call from an APK fails
 * before it leaves the device. Plain HTTP is not an option either: the host 301-redirects
 * http → https.
 *
 * WHAT IT DOES
 * Writes an Android network security config that trusts that one certificate **for that one
 * hostname only** (alongside the system CAs, so it keeps working the moment a real
 * certificate is installed). Production (apimac.zyncbook.com) is untouched and still uses
 * the normal system trust store.
 *
 * REMOVE THIS once the backend team installs a proper certificate on the UAT host — it is a
 * testing accommodation, not a shipping practice. Nothing here weakens TLS for any other
 * host, and no certificate pinning is applied to production.
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const UAT_HOST = "apimacuat.zyncbook.com";
const RAW_CERT_NAME = "uat_apimacuat"; // → res/raw/uat_apimacuat.pem, referenced as @raw/uat_apimacuat

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withUatCertificate.js — do not edit by hand. -->
<network-security-config>
    <!-- Production API is plain HTTP; keep cleartext allowed and use system CAs everywhere. -->
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>

    <!-- UAT/staging only: also trust the self-signed certificate that host currently serves.
         System CAs stay listed first, so a properly issued certificate just works. -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">${UAT_HOST}</domain>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="@raw/${RAW_CERT_NAME}" />
        </trust-anchors>
    </domain-config>
</network-security-config>
`;

function withUatCertificateFiles(config) {
  return withDangerousMod(config, [
    "android",
    async (cfg) => {
      const resDir = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res");
      const rawDir = path.join(resDir, "raw");
      const xmlDir = path.join(resDir, "xml");
      fs.mkdirSync(rawDir, { recursive: true });
      fs.mkdirSync(xmlDir, { recursive: true });

      const pem = path.join(__dirname, "certs", "apimacuat.pem");
      if (!fs.existsSync(pem)) {
        throw new Error(
          `withUatCertificate: missing ${pem}. Re-export it with:\n` +
            `  openssl s_client -connect ${UAT_HOST}:443 -servername ${UAT_HOST} </dev/null 2>/dev/null | openssl x509 -outform PEM > frontend/plugins/certs/apimacuat.pem`
        );
      }
      fs.copyFileSync(pem, path.join(rawDir, `${RAW_CERT_NAME}.pem`));
      fs.writeFileSync(path.join(xmlDir, "network_security_config.xml"), NETWORK_SECURITY_CONFIG, "utf8");
      return cfg;
    },
  ]);
}

function withUatCertificateManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$["android:networkSecurityConfig"] = "@xml/network_security_config";
    return cfg;
  });
}

module.exports = function withUatCertificate(config) {
  return withUatCertificateManifest(withUatCertificateFiles(config));
};
